//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasımatablosu
    {
        public int ıd { get; set; }
        public string mod { get; set; }
        public string tturu { get; set; }
        public string bülke { get; set; }
        public string pakett { get; set; }
        public string brmb { get; set; }
        public string brmi { get; set; }
        public string pbirimi { get; set; }
        public Nullable<int> ucret { get; set; }
        public string gülke { get; set; }
        public string gsehir { get; set; }
    }
}
